<?php

return [
    'add' => 'Tambah',
    'create' => 'Create',
    'list' => 'List',
    'show' => 'Show',
    'entries' => 'Entries',
    'search' => 'Search',
    'view' => 'View',
    // 'action' => 'Action',
    'edit' => 'Edit',
    'delete' => 'Hapus',
    'save' => 'Save',
    'reject' => 'Reject',
    'approve' => 'Setujui',
    'pleaseSelect' => 'Please select',
    'areYouSure' => 'Are you sure?',
    'allRightsReserved' => 'All rights reserved.',
    'downloadFile' => 'Download file',
    'toggleNavigation' => 'Toggle navigation',
    'home' => 'Home',
    'youAreLoggedIn' => 'You are logged in!',
    'user_name' => 'Name',
    'reset_password' => 'Reset Password',
    'login' => 'Login',
    'remember_me' => 'Remember me',
    'forgot_password' => 'Forgot your password?',
    'register' => 'Registrasi',
    'login_email' => 'Email',
    'login_password' => 'Password',
    'login_password_confirmation' => 'Password confirmation',
    'yes' => 'Yes',
    'no' => 'No',
    'view_file' => 'View file',
    'verifyYourUser' => 'To finish your registration - site asks you to verify your email',
    'clickHereToVerify' => 'Click here to verify',
    'thankYouForUsingOurApplication' => 'Thank you for using our website',
    'verifyYourEmail' => 'Please verify your email',
    'emailVerificationSuccess' => 'User email verified successfully',
    'yourAccountNeedsAdminApproval' => 'Your accounts needs an administrator approval in order to log in',
    'timeFrom' => 'From',
    'timeTo' => 'To',
    'filterDate' => 'Filter by date',
    'reports' => 'Reports',
    'year' => 'Year',
    'month' => 'Month',
    'logout' => 'Logout',
    'calendar' => 'Calendar',
    'dashboard' => 'Dashboard',
    'datatables' => [
        'copy' => 'Copy',
        'csv' => 'CSV',
        'excel' => 'Excel',
        'pdf' => 'PDF',
        'print' => 'Print',
        'colvis' => 'Column visibility',
        'delete' => 'Delete selected',
        'zero_selected' => 'No rows selected',
    ],
    'restore' => 'Restore',
    'permadel' => 'Delete Permanently',
    'all' => 'All',
    'trash' => 'Trash',
    'update' => 'Update',
    'no_entries_in_table' => 'No entries in table',
    'custom_controller_index' => 'Custom controller index.',
    'back_to_list' => 'Back to list',
    'category' => 'Category',
    'categories' => 'Categories',
    'sample_category' => 'Sample category',
    'questions' => 'Questions',
    'question' => 'Question',
    'answer' => 'Answer',
    'sample_question' => 'Sample question',
    'sample_answer' => 'Sample answer',
    'faq_management' => 'FAQ Management',
    'administrator_can_create_other_users' => 'Administrator (can create other users)',
    'simple_user' => 'Simple user',
    'title' => 'Title',
    'roles' => 'Roles',
    'role' => [
        'title' => 'Roles',
        'title_singular' => 'Role',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'title' => 'Title',
            'title_helper' => '',
            'permissions' => 'Permissions',
            'permissions_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],
    'user_management' => 'User management',
    'users' => 'Users',
    'user' => [
        'title' => 'Users',
        'title_singular' => 'User',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'name' => 'Name',
            'name_helper' => '',
            'email' => 'Email',
            'email_helper' => '',
            'email_verified_at' => 'Email verified at',
            'email_verified_at_helper' => '',
            'password' => 'Password',
            'password_helper' => '',
            'roles' => 'Roles',
            'roles_helper' => '',
            'remember_token' => 'Remember Token',
            'remember_token_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
            'phone' => 'No Ponsel',
            'phone_helper' => '',
        ],
    ],
    'name' => 'Name',
    'remember_token' => 'Remember token',
    'permissions' => 'Permissions',
    'user_actions' => 'User actions',
    'action' => 'Action',
    'action_model' => 'Action model',
    'action_id' => 'Action id',
    'time' => 'Time',
    'campaign' => 'Campaign',
    'campaigns' => 'Campaigns',
    'description' => 'Description',
    'valid_from' => 'Valid from',
    'valid_to' => 'Valid to',
    'discount_amount' => 'Discount amount',
    'discount_percent' => 'Discount percent',
    'coupons_amount' => 'Coupons amount',
    'coupons' => 'Coupons',
    'code' => 'Code',
    'redeem_time' => 'Redeem time',
    'coupon_management' => 'Coupon Management',
    'time_management' => 'Time management',
    'projects' => 'Projects',
    'time_entries' => 'Time entries',
    'work_type' => 'Work type',
    'work_types' => 'Work types',
    'project' => 'Project',
    'start_time' => 'Start time',
    'end_time' => 'End time',
    'expense_category' => 'Expense Category',
    'expense_categories' => 'Expense Categories',
    'expense_management' => 'Expense Management',
    'expenses' => 'Expenses',
    'expense' => 'Expense',
    'entry_date' => 'Entry date',
    'amount' => 'Amount',
    'income_categories' => 'Income categories',
    'monthly_report' => 'Monthly report',
    'companies' => 'Companies',
    'company_name' => 'Company name',
    'address' => 'Address',
    'website' => 'Website',
    'contact_management' => 'Contact management',
    'contacts' => 'Contacts',
    'company' => 'Company',
    'first_name' => 'First name',
    'last_name' => 'Last name',
    'phone' => 'Phone',
    'phone1' => 'Phone 1',
    'phone2' => 'Phone 2',
    'skype' => 'Skype',
    'photo' => 'Photo (max 8mb)',
    'category_name' => 'Category name',
    'product_management' => 'Product management',
    'products' => 'Products',
    'product_name' => 'Product name',
    'price' => 'Price',
    'tags' => 'Tags',
    'tag' => 'Tag',
    'photo1' => 'Photo1',
    'photo2' => 'Photo2',
    'photo3' => 'Photo3',
    'statuses' => 'Statuses',
    'task_management' => 'Task management',
    'tasks' => 'Tasks',
    'status' => 'Status',
    'attachment' => 'Attachment',
    'due_date' => 'Due date',
    'assigned_to' => 'Assigned to',
    'assets' => 'Assets',
    'asset' => 'Asset',
    'serial_number' => 'Serial number',
    'location' => 'Location',
    'locations' => 'Locations',
    'assigned_user' => 'Assigned (user)',
    'notes' => 'Notes',
    'assets_history' => 'Assets history',
    'assets_management' => 'Assets management',
    'slug' => 'Slug',
    'content_management' => 'Content management',
    'text' => 'Text',
    'excerpt' => 'Excerpt',
    'featured_image' => 'Featured image',
    'pages' => 'Pages',
    'axis' => 'Axis',
    'group_by' => 'Group by',
    'chart_type' => 'Chart type',
    'create_new_report' => 'Create new report',
    'no_reports_yet' => 'No reports yet.',
    'created_at' => 'Created at',
    'updated_at' => 'Updated at',
    'deleted_at' => 'Deleted at',
    'reports_x_axis_field' => 'X-axis - please choose one of date/time fields',
    'reports_y_axis_field' => 'Y-axis - please choose one of number fields',
    'select_crud_placeholder' => 'Please select one of your CRUDs',
    'select_dt_placeholder' => 'Please select one of date/time fields',
    'aggregate_function_use' => 'Aggregate function to use',
    'x_axis_group_by' => 'X-axis group by',
    'x_axis_field' => 'X-axis field (date/time)',
    'y_axis_field' => 'Y-axis field',
    'integer_float_placeholder' => 'Please select one of integer/float fields',
    'change_notifications_field_1_label' => 'Send email notification to User',
    'change_notifications_field_2_label' => 'When Entry on CRUD',
    'select_users_placeholder' => 'Please select one of your Users',
    'is_created' => 'is created',
    'is_updated' => 'is updated',
    'is_deleted' => 'is deleted',
    'notifications' => 'Notifications',
    'notify_user' => 'Notify User',
    'when_crud' => 'When CRUD',
    'create_new_notification' => 'Create new Notification',
    'stripe_transactions' => 'Stripe Transactions',
    'upgrade_to_premium' => 'Upgrade to Premium',
    'messages' => 'Messages',
    'you_have_no_messages' => 'You have no messages.',
    'all_messages' => 'All Messages',
    'new_message' => 'New message',
    'outbox' => 'Outbox',
    'inbox' => 'Inbox',
    'recipient' => 'Recipient',
    'subject' => 'Subject',
    'message' => 'Message',
    'send' => 'Send',
    'reply' => 'Reply',
    'calendar_sources' => 'Calendar sources',
    'new_calendar_source' => 'Create new calendar source',
    'crud_title' => 'Crud title',
    'crud_date_field' => 'Crud date field',
    'prefix' => 'Prefix',
    'label_field' => 'Label field',
    'suffix' => 'Sufix',
    'no_calendar_sources' => 'No calendar sources yet.',
    'crud_event_field' => 'Event label field',
    'create_new_calendar_source' => 'Create new Calendar Source',
    'edit_calendar_source' => 'Edit Calendar Source',
    'client_management' => 'Client management',
    'client_management_settings' => 'Client management settings',
    'country' => 'Country',
    'client_status' => 'Client status',
    'clients' => 'Clients',
    'client_statuses' => 'Client statuses',
    'currencies' => 'Currencies',
    'main_currency' => 'Main currency',
    'documents' => 'Documents',
    'file' => 'File',
    'income_source' => 'Income source',
    'income_sources' => 'Income sources',
    'fee_percent' => 'Fee percent',
    'note_text' => 'Note text',
    'client' => 'Client',
    'start_date' => 'Start date',
    'budget' => 'Budget',
    'project_status' => 'Project status',
    'project_statuses' => 'Project statuses',
    'transactions' => 'Transactions',
    'transaction_types' => 'Transaction types',
    'transaction_type' => 'Transaction type',
    'transaction_date' => 'Transaction date',
    'currency' => 'Currency',
    'current_password' => 'Current password',
    'new_password' => 'New password',
    'change_password' => 'Change password',
    'reset_password_woops' => '<strong>Whoops!</strong> There were problems with input:',
    'email_line1' => 'You are receiving this email because we received a password reset request for your account.',
    'email_line2' => 'If you did not request a password reset, no further action is required.',
    'email_greet' => 'Hello',
    'email_regards' => 'Regards',
    'confirm_password' => 'Confirm password',
    'if_you_are_having_trouble' => 'If youâ€™re having trouble clicking the',
    'copy_paste_url_bellow' => 'button, copy and paste the URL below into your web browser:',
    'registration' => 'Registration',
    'not_approved_title' => 'You are not approved',
    'not_approved_p' => 'Your account is still not approved by administrator. Please, be patient and try again later.',
    'there_were_problems_with_input' => 'There were problems with input',
    'whoops' => 'Whoops!',
    'file_contains_header_row' => 'File contains header row?',
    'csvImport' => 'CSV Import',
    'csv_file_to_import' => 'CSV file to import',
    'parse_csv' => 'Parse CSV',
    'import_data' => 'Import data',
    'imported_rows_to_table' => 'Imported :rows rows to :table table',
    'subscription-billing' => 'Subscriptions',
    'subscription-payments' => 'Payments',
    'basic_crm' => 'Basic CRM',
    'select_all' => 'Select all',
    'deselect_all' => 'Deselect all',
    'team-management' => 'Teams',
    'team-management-singular' => 'Team',
    'site_title' => 'Sistem Keluhan Pelanggan',
    'ticket_request' => 'Tiket & Permintaan',
    'report' => 'Laporan',
    'reporthumas' => 'Rekap Permintaan',
    'reportdistribusi' => 'Rekap Keluhan',
    'userManagement' => [
        'title' => 'User Management',
        'title_singular' => 'User Management',
        'fields' => [],
    ],
    'permission' => [
        'title' => 'Permissions',
        'title_singular' => 'Permission',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'title' => 'Title',
            'title_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],
    'master' => [
        'title' => 'Master',
        'title_singular' => 'Masters',
        'fields' => [],
    ],

    'customer' => [
        'title' => 'Pelanggan',
        'title_singular' => 'Pelanggan',
        'fields' => [
            'code' => 'Kode',
            'name' => 'Nama Lengkap',
            'email' => 'Email',
            'phone' => 'No Ponsel',
            'type' => 'Tipe',
            'password' => 'Kata Sandi',
            'gender' => 'Jenis Kelamin',
            'address' => 'Alamat'
        ]
    ],
    'category' => [
        'title' => 'Kategori',
        'title_singular' => 'Kategori',
        'fields' => [
            'code' => 'Kode',
            'name' => 'Nama Kategori',
            'category_group_id' => 'Group',
            'category_type_id' => 'Type',
        ]
    ],
    'dapertement' => [
        'title' => 'Departemen',
        'title_singular' => 'Departemen',
        'fields' => [
            'code' => 'Kode',
            'name' => 'Nama Departemen',
            'description' => 'Deskripsi'
        ]
    ],
    'subdapertement' => [
        'title' => 'Sub Departemen',
        'title_singular' => 'Sub Departemen',
        'fields' => [
            'code' => 'Kode',
            'name' => 'Nama Sub Departemen',
            'description' => 'Deskripsi',
            'dapertement' => 'Deskripsi'
        ]
    ],
    'staff' => [
        'title' => 'Staff',
        'title_singular' => 'Staff',
        'fields' => [
            'code' => 'Kode',
            'name' => 'Nama Staff',
            'pbk' => 'Pilih Pbk',
            'NIK' => 'NIK',
            'description' => 'Deskripsi',
            'phone' => 'No Ponsel',
            'dapertement' => "Dapertemen",
            'subdapertement' => "Sub Dapertemen",
            'work_unit' => 'Unit Kerja',
            'director' => "Direksi",
            'area' => "Area",
            'job' => "pekerjaan"
        ]
    ],
    'ticket' => [
        'title' => 'Tiket',
        'title_singular' => 'Tiket',
        'fields' => [
            'code' => 'Kode',
            'title' => 'Nama Tiket',
            'image' => 'Bukti Gambar',
            'video' => 'Bukti Video',
            'lat' => 'Kordinat Latitude',
            'lng' => 'Kordinat Longtitude',
            'status' => 'Status',
            'address' => 'Alamat',
            'category' => 'Kategori',
            'customer' => 'Nama Pelanggan',
            'customer_code' => 'Kode Pelanggan',
            'description' => 'Deskripsi',
            'date' => 'Tanggal',
            'departement' => 'Nama Departement',
            'memo' => 'Memo',
            'creator' => 'Oleh',
        ]
    ],
    'action' => [
        'print_service' => 'Print Permintaan Service',
        'print_SPK' => 'Print SPK',
        'print_Report' => 'Print Laporan Service',
        'title' => 'Tindakan',
        'title_singular' => 'Tindakan',
        'fields' => [
            'code' => 'Kode',
            'title' => 'Nama Tindakan',
            'description' => 'Deskripsi',
            'status' => 'Status',
            'dapertement' => 'Departemen',
            'subdapertement' => 'Sub Departemen',
            'ticket' => 'Tiket',
            'start' => 'Waktu Mulai',
            'end' => 'Waktu Selesai',
            'staff' => 'Pegawai',
            'memo' => 'Memo'
        ]
    ],
    'action_staff' => [
        'title' => 'Pegawai',
        'title_singular' => 'Pegawai yang bertugas',
        'fields' => [
            'code' => 'Kode',
            'description' => 'Deskripsi',
            'name' => 'Nama Pegawai',
            'todo' => 'Pekerja',
            'dapertement' => 'Dapertement',
            'phone' => 'No Ponsel',
            'status' => 'Status',
            'description' => 'Deskripsi'
        ]
    ],
    'customerrequest' => [
        'title' => 'Permintaan Pelanggan',
        'title_singular' => 'Permintaan',
        'fields' => [
            'code' => 'Kode',
            'name' => 'Nama',
            'phone' => 'Telfon',
            'address' => 'Alamat',
            'status' => 'Status',
            'img' => 'Foto',
        ]
    ],
    'ctmrequest' => [
        'title' => 'Baca Mandiri',
        'title_singular' => 'Permintaan',
        'fields' => [
            'norek' => 'No. SBG',
            'name' => 'Nama',
            'wmmeteran' => 'Hasil Bacaan',
            'address' => 'Alamat',
            'status' => 'Status',
            'img' => 'Foto',
            'year' => 'Tahun',
            'periode' => 'Periode',
            'dateRead' => 'Tanggal Baca',
            'month' => 'Bulan',
        ]
    ],
    'pbk' => [
        'title' => 'Operator Pembaca',
        'title_singular' => 'Pembaca',
        'fields' => [
            'name' => 'Nama',
            'number' => 'No. HP',
            'status' => 'Status',
        ]
    ],
    'segelmeter' => [
        'title' => 'Info Tunggakan',
        'norekening' => 'No Rekening',
        'name' => 'Nama ',
        'address' => 'Alamat',
        'tunggakan' => 'Jumlah Tunggakan',
        'status' => 'Status Tunggakan'
    ],
    'laporan_audited' => [
        'title' => 'Keuangan Audited'
    ],
    'lock' => [
        'title' => 'Info Segel',
        'customer' => 'Kode Pelanggan',
        'code' => 'Kode',
        'status' => 'Status',
        'subdapertement' => 'Subdpaertemen',
        'description' => 'Deskripsi',
        'start' => 'Start',
        'end' => 'End',
        'dapertement' => 'Dapertemen',
        'type' => 'Type',
        'staff_id' => 'ID Staff',
        'staff_name' => 'Nama Staff',
        'fields' => [
            'noSbg' => 'Kode Pelanggan',
            'customer' => 'Nama Pelanggan',
            'staff_id' => 'ID Staff',
            'staff_name' => 'Nama Staff',
            'type' => 'Tindakan',
            'memo' => 'Memo',

        ]
    ],
    'audited' => [
        'title' => 'Laporan Keuangan Audited',
        'title_singular' => 'Audited',
        'fields' => [
            'name' => 'Nama',
            'periode' => 'Periode',
            'file' => 'PDF',
        ]
    ],
    'categoryWAs' => 'Kategori WA',
    'categoryWA' => [
        'title' => 'Kategori WA',
        'title_singular' => 'Kategori WA',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'title' => 'Title',
            'title_helper' => '',
            'name' => 'Nama',
            'name_helper' => '',
            'code' => 'Kode',
            'code_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'WaTemplates' => 'Template WA',
    'WaTemplate' => [
        'title' => 'Template WA',
        'title_singular' => 'Template WA',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'title' => 'Title',
            'title_helper' => '',
            'name' => 'Nama',
            'name_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'message' => 'Pesan',
            'message_helper' => '',
            'code' => 'Kode',
            'code_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],


    'was' => 'Whatsapp',
    'wa' => [
        'title' => 'Whatsapp',
        'title_singular' => 'Whatsapp',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'title' => 'Title',
            'title_helper' => '',
            'phone' => 'Nomor Telepon',
            'phone_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'message' => 'Pesan',
            'message_helper' => '',
            'id_wa' => 'ID Whatsapp',
            'id_wa_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],
    'wablasts' => 'Whatsapp',
    'wablast' => [
        'title' => 'Whatsapp',
        'title_singular' => 'Whatsapp',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'title' => 'Title',
            'title_helper' => '',
            'phone' => 'Nomor Telepon',
            'phone_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'template' => 'Template',
            'template_helper' => '',
            'type' => 'Tipe',
            'type_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'message' => 'Pesan',
            'message_helper' => '',
            'id_wa' => 'ID Whatsapp',
            'id_wa_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'workUnits' => 'Unit Kerja',
    'workUnit' => [
        'title' => 'Unit Kerja',
        'title_singular' => 'Unit Kerja',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'name' => 'Nama',
            'name_helper' => '',
            'code' => 'Kode',
            'code_helper' => '',
            'location' => 'Lokasi',
            'location_helper' => '',
            'lat' => 'Lat',
            'lat_helper' => '',
            'lng' => 'Lng',
            'radius' => 'Radius',
            'radius_helper' => '',
            'lng_helper' => '',
            'serial_number' => 'Nomor Urut',
            'serial_number_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'proposalwms' => 'Usulan Pergantian WM',
    'proposalwm' => [
        'title' => 'Usulan Pergantian WM',
        'title_singular' => 'Usulan Pergantian WM',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'name' => 'Nama',
            'name_helper' => '',
            'code' => 'Kode',
            'code_helper' => '',
            'memo' => 'Memo',
            'memo_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'action' => 'Tindakan',
            'memo_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'nomorrekening' => 'No.SBG',
            'nomorrekening_helper' => '',
            'subdapertement_id' => 'Tindakan',
            'subdapertement_id_helper' => '',
            'status_wm' => 'Status WM',
            'status_wm_helper' => '',
            'priority' => 'Prioritas',
            'priority_helper' => '',
            'customer_id' => 'No.SBG',
            'customer_id_helper' => '',
            'customer' => 'Pelanggan',
            'customer_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],


    'actionWms' => 'Tindakan',
    'actionWms' => [
        'title' => 'Tindakan',
        'title_singular' => 'Tindakan',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'name' => 'Nama',
            'name_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'noWM1' => 'No Water Meter (lama)',
            'noWM1_helper' => '',
            'standWM1' => 'Stand Water Meter (lama)',
            'standWM1_helper' => '',
            'brandWM1' => 'Brand Water Meter (lama)',
            'brandWM1_helper' => '',
            'noWM2' => 'No Water Meter (baru)',
            'noWM2_helper' => '',
            'standWM2' => 'Stand Water Meter (baru)',
            'standWM2_helper' => '',
            'brandWM2' => 'Brand Water Meter (baru)',
            'brandWM2_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'schedule' => 'Jadwal',
    'schedule' => [
        'title' => 'Jadwal',
        'title_singular' => 'Jadwal',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'title' => 'Keterangan',
            'title_helper' => '',
            'time' => 'Waktu',
            'time_helper' => '',
            'start' => 'Mulai',
            'start_helper' => '',
            'end' => 'Berakhir',
            'end_helper' => '',
            'value' => 'Nilai',
            'value_helper' => '',
            'queue' => 'Urutan',
            'queue_helper' => '',
            'day' => 'Hari',
            'day_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'absence' => 'Absen',
    'absence' => [
        'title' => 'Absen',
        'title_singular' => 'Absen',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'staff' => 'Nama',
            'staff_helper' => '',
            'title' => 'Keterangan',
            'title_helper' => '',
            'lat' => 'Lat',
            'lat_helper' => '',
            'lng' => 'Lng',
            'lng_helper' => '',
            'register' => 'Waktu',
            'register_helper' => '',
            'absence_category' => 'Kategori',
            'absence_category_helper' => '',
            'late' => 'Tepat',
            'late_helper' => '',
            'image' => 'Foto',
            'image_helper' => '',
            'staff_image' => 'Foto Staff',
            'staff_image_helper' => '',
            'value' => 'Nilai',
            'value_helper' => '',
            'queue' => 'Urutan',
            'queue_helper' => '',
            'day' => 'Hari',
            'day_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
            // tambahan untuk laporan
            'staff_code' => 'Kode',
            'staff_name' => 'Nama',
            'job_name' => 'Jabatan',
            'abtotal' => 'Total Hari',
            'jumlah_sabtuminggu' => 'Jumlah Sabtu Minggu',
            'total_efektif_kerja' => 'Efektif Kerja',
            'hadir' => 'Hadir',
            'izin' => 'Izin',
            'dinas_luar' => 'Dinas Luar',
            'cuti' => 'Cuti',
            'jam_hadir' => 'Jam Hadir',
            'jam_istirahat' => 'Jam Istirahat',
            'jam_lembur' => 'Jam Lembur',
            'jam_dinas_dalam' => 'Jam Dinas Dalam',
            'subdapertement' => 'Sub Bagian',
            'jumlah_libur' => 'Jumlah Libur',
            'alfa' => 'Jumlah Alfa',
            'dinas_dalam'  => 'Jumlah Dinas Dalam',
            'jam_terlambat' => 'Total Jam Terlambat',
            'terlambat' => 'Jumlah Terlambat',
            'jam_permisi' => 'Total Jam Permisi',
            'permisi' => 'Jumlah Permisi',

        ],
    ],


    'holiday' => 'Libur',
    'holiday' => [
        'title' => 'Libur',
        'title_singular' => 'Libur',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'title' => 'Keterangan',
            'title_helper' => '',
            'date' => 'Tanggal',
            'date_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'day' => 'Hari',
            'day_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'shift' => 'Shift',
    'shift' => [
        'title' => 'Shift',
        'title_singular' => 'Shift',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'name' => 'Nama User',
            'name_helper' => '',
            'shift_title' => 'Shift',
            'shift_title_helper' => '',
            'shift_date' => 'Tanggal',
            'shift_date_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'dapertement_name' => 'Dapertement',
            'dapertement_name_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],


    'duty' => 'Dinas',
    'duty' => [
        'title' => 'Dinas',
        'title_singular' => 'Dinas',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'staff_name' => 'Nama Staff',
            'staff_name_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'type' => 'Tipe',
            'type_helper' => '',
            'date' => 'Mulai',
            'date_helper' => '',
            'end' => 'Berakhir',
            'end_helper' => '',
            'time' => 'Jam',
            'time_helper' => '',
            'file' => 'File',
            'file_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'start' => 'Tanggal Mulai',
            'start_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'extra' => 'Lembur',
    'extra' => [
        'title' => 'Lembur',
        'title_singular' => 'Lembur',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'staff_name' => 'Nama Staff',
            'staff_name_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'type' => 'Tipe',
            'type_helper' => '',
            'time' => 'Jam',
            'time_helper' => '',
            'date' => 'Mulai',
            'date_helper' => '',
            'end' => 'Berakhir',
            'end_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'start' => 'Tanggal Mulai',
            'start_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'excuse' => 'Permisi',
    'excuse' => [
        'title' => 'Permisi',
        'title_singular' => 'Permisi',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'staff_name' => 'Nama Staff',
            'staff_name_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'type' => 'Tipe',
            'type_helper' => '',
            'time' => 'Jam',
            'time_helper' => '',
            'date' => 'Mulai',
            'date_helper' => '',
            'end' => 'Berakhir',
            'end_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'start' => 'Tanggal Mulai',
            'start_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'leave' => 'Cuti',
    'leave' => [
        'title' => 'Cuti',
        'title_singular' => 'Cuti',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'staff_name' => 'Nama Staff',
            'staff_name_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'type' => 'Tipe',
            'type_helper' => '',
            'time' => 'Jam',
            'time_helper' => '',
            'date' => 'Mulai',
            'date_helper' => '',
            'end' => 'Berakhir',
            'end_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'start' => 'Tanggal Mulai',
            'start_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
            'file_png' => 'File Pengajuan',
            'file_png_helper' => '',
            'file_p' => 'File Persetujuan',
            'file_p_helper' => '',
        ],
    ],

    'workPermit' => 'Izin',
    'workPermit' => [
        'title' => 'Izin',
        'title_singular' => 'Izin',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'staff_name' => 'Nama Staff',
            'staff_name_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'type' => 'Tipe',
            'type_helper' => '',
            'time' => 'Jam',
            'time_helper' => '',
            'date' => 'Mulai',
            'date_helper' => '',
            'end' => 'Berakhir',
            'end_helper' => '',
            'file' => 'File',
            'file_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'start' => 'Tanggal Mulai',
            'start_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],

    'geolocation_off' => 'Izin',
    'geolocation_off' => [
        'title' => 'Izin',
        'title_singular' => 'Izin',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'staff_name' => 'Nama Staff',
            'staff_name_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'type' => 'Tipe',
            'type_helper' => '',
            'time' => 'Jam',
            'time_helper' => '',
            'date' => 'Mulai',
            'date_helper' => '',
            'end' => 'Berakhir',
            'end_helper' => '',
            'file' => 'File',
            'file_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'start' => 'Tanggal Mulai',
            'start_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],


    'forget' => 'Lupa Absen',
    'forget' => [
        'title' => 'Lupa Absen',
        'title_singular' => 'Lupa Absen',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'staff_name' => 'Nama Staff',
            'staff_name_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'type' => 'Tipe',
            'type_helper' => '',
            'time' => 'Jam',
            'time_helper' => '',
            'date' => 'Mulai',
            'date_helper' => '',
            'end' => 'Berakhir',
            'end_helper' => '',
            'file' => 'File',
            'file_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'start' => 'Tanggal Mulai',
            'start_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],


    'location' => 'Pindah Lokasi',
    'location' => [
        'title' => 'Pindah Lokasi',
        'title_singular' => 'Pindah Lokasi',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'staff_name' => 'Nama Staff',
            'staff_name_helper' => '',
            'category' => 'Kategori',
            'category_helper' => '',
            'type' => 'Tipe',
            'type_helper' => '',
            'time' => 'Jam',
            'time_helper' => '',
            'date' => 'Mulai',
            'date_helper' => '',
            'end' => 'Berakhir',
            'end_helper' => '',
            'file' => 'File',
            'file_helper' => '',
            'description' => 'Deskripsi',
            'description_helper' => '',
            'status' => 'Status',
            'status_helper' => '',
            'start' => 'Tanggal Mulai',
            'start_helper' => '',
            'created_at' => 'Created at',
            'created_at_helper' => '',
            'updated_at' => 'Updated at',
            'updated_at_helper' => '',
            'deleted_at' => 'Deleted at',
            'deleted_at_helper' => '',
        ],
    ],



    'shift_parent' => [
        'title' => 'Shift',
        'title_singular' => 'Shift',
        'fields' => [
            'title' => 'Shift',
            'title_helper' => '',
            'dapertement' => 'dapertement',
            'dapertement_helper' => '',
            'job' => 'Pekerjaan',
            'job_helper' => '',
            'work_unit' => 'Unit Kerja',
            'work_unit_helper' => '',

        ],
    ],

    'shift_group' => [
        'title' => 'Shift',
        'title_singular' => 'Shift',
        'fields' => [
            'title' => 'Shift',
            'title_helper' => '',
            'code' => 'Code',
            'code_helper' => '',
            'queue' => 'queue',
            'queue_helper' => '',
            'job' => 'Pekerjaan',
            'job_helper' => '',
            'work_unit' => 'Unit Kerja',
            'work_unit_helper' => '',

        ],
    ],

    'work_type' => 'Jadwal',
    'work_type' => [
        'title' => 'Jadwal',
        'title_singular' => 'Jadwal',
        'fields' => [
            'title' => 'Jadwal',
            'title_helper' => '',
            'type' => "Tipe",
            'type_helper' => "",
            'code' => 'Kode',
            'code_helper' => '',
        ]
    ],

    'work_type_day' => 'Jadwal',
    'work_type_day' => [
        'title' => 'Jadwal',
        'title_singular' => 'Jadwal',
        'fields' => [
            'category' => 'Jadwal',
            'category_helper' => '',
            'time' => "Tipe",
            'time_helper' => "",
            'day' => 'Hari',
            'day_helper' => '',
            'duration' => 'Durasi Kerja',
            'duration_helper' => '',
            'duration_exp' => 'Toleransi',
            'duration_exp_helper' => '',
            'time_in' => 'Masuk',
            'time_in_helper' => '',
            'time_out' => 'Pulang',
            'time_out_helper' => '',
            'time_breakin' => 'Istirahat Mulai',
            'time_breakin_helper' => '',
            'time_breakout' => 'Istirahat Selesai',
            'time_breakout_helper' => ''
        ]
    ],

    'shift_change' => 'Tukar Shift',
    'shift_change' => [
        'title' => 'Tukar Shift',
        'title_singular' => 'Tukar Shift',
        'fields' => [
            'title' => 'Tukar Shift',
            'title_helper' => '',
            'name1' => 'Staff Penukar',
            'name1_helper' => '',
            'name2' => 'Staff Ditukar',
            'name2_helper' => '',
            'shift1' => 'Shift Penukar',
            'shift1_helper' => '',
            'shift2' => 'Shift Ditukar',
            'shift2_helper' => '',
            'status' => 'Status',
            'status_helper' => '',

        ],
    ],


    'staffSpecial' => 'Staff Spesial',
    'staffSpecial' => [
        'title' => 'Staff Spesial',
        'title_singular' => 'Staff Spesial',
        'fields' => [
            'id' => 'ID',
            'id_helper' => '',
            'name' => 'Nama',
            'name_helper' => '',
            'expired_date' => 'Batas Waktu',
            'expired_date_helper' => '',
            'fingerprint' => 'Fingerprint',
            'fingerprint_helper' => '',
            'camera' => 'Kamera',
            'camera_helper' => '',
            'gps' => 'GPS',
            'gps_helper' => '',
            'staff' => 'Staff',
            'staff_helper' => '',
            'phone' => 'Telepon',
            'phone_helper' => '',
        ],
    ],


];
